// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

using System.Collections.Immutable;
using Bicep.Core.TypeSystem;
using Bicep.Core.TypeSystem.Types;

namespace Bicep.Core.TestFramework;

/// <summary>
/// The declared type of the compiler-provided <c>target</c> symbol.
///
/// Every object here is closed: it declares no additional properties, so an assertion that misspells a
/// fact name is reported as an unknown property instead of quietly evaluating to a null that would make
/// the policy pass.
/// </summary>
public static class TestTargetType
{
    public const string ResourcesPropertyName = "resources";
    public const string ModulesPropertyName = "modules";
    public const string ImportsPropertyName = "imports";
    public const string WithModulesPropertyName = "withModules";

    public const string NamePropertyName = "name";
    public const string SymbolicNamePropertyName = "symbolicName";
    public const string EvaluatedPropertyName = "evaluated";
    public const string OutputsPropertyName = "outputs";
    public const string InstanceIdPropertyName = "instanceId";
    public const string TypePropertyName = "type";
    public const string ExistingPropertyName = "existing";
    public const string PathPropertyName = "path";
    public const string ResolvedFilePropertyName = "resolvedFile";
    public const string SymbolsPropertyName = "symbols";
    public const string WildcardPropertyName = "wildcard";
    public const string FilePropertyName = "file";
    public const string LinePropertyName = "line";
    public const string ParametersPropertyName = "parameters";
    public const string RequiredPropertyName = "required";
    public const string HasDefaultPropertyName = "hasDefault";
    public const string TargetScopePropertyName = "targetScope";
    public const string WaitsForPropertyName = "waitsFor";

    /// <summary>
    /// The top-level keys of a resource body an evaluated instance exposes. These are what the author
    /// wrote in the declaration, computed for the case; <c>dependsOn</c> and the internals of a module's
    /// deployment are generated by the compiler and deliberately absent.
    /// </summary>
    public static readonly ImmutableArray<string> EvaluatedBodyPropertyNames = ["properties", "location", "sku", "kind", "identity", "tags", "zones"];

    /// <summary>
    /// Whether a value is one evaluated resource instance, so a caller can tell a read of its body from
    /// a read of an output that happens to share a key name.
    /// </summary>
    public static bool IsEvaluatedResourceFact(TypeSymbol type) => ReferenceEquals(type, EvaluatedResourceFact);

    private static readonly ObjectType ResourceFact = new(
        "resourceFact",
        TypeSymbolValidationFlags.Default,
        [
            new NamedTypeProperty(SymbolicNamePropertyName, LanguageConstants.String, TypePropertyFlags.ReadOnly, "The symbolic name of the declaration."),
            new NamedTypeProperty(TypePropertyName, LanguageConstants.String, TypePropertyFlags.ReadOnly, "The resource type without its API version, for example 'Microsoft.Sql/servers'."),
            new NamedTypeProperty(ExistingPropertyName, LanguageConstants.Bool, TypePropertyFlags.ReadOnly, "Whether the declaration references an existing resource rather than declaring a new one."),
            new NamedTypeProperty(FilePropertyName, LanguageConstants.String, TypePropertyFlags.ReadOnly, "The declaring file, relative to the selector root and always using '/' separators."),
            new NamedTypeProperty(LinePropertyName, LanguageConstants.Int, TypePropertyFlags.ReadOnly, "The 1-based line the declaration starts on."),
            new NamedTypeProperty(WaitsForPropertyName, new TypedArrayType(LanguageConstants.String, TypeSymbolValidationFlags.Default), TypePropertyFlags.ReadOnly, "The symbolic names of the resources and modules in the same file that must be deployed first, directly or not, in source order. Explicit dependsOn entries, references and parent resources all count; variables are followed; existing resources are followed but never listed, because nothing deploys them."),
        ],
        null);

    private static readonly ObjectType ModuleFact = new(
        "moduleFact",
        TypeSymbolValidationFlags.Default,
        [
            new NamedTypeProperty(SymbolicNamePropertyName, LanguageConstants.String, TypePropertyFlags.ReadOnly, "The symbolic name of the declaration."),
            new NamedTypeProperty(PathPropertyName, LanguageConstants.String, TypePropertyFlags.ReadOnly, "The path exactly as spelled in source."),
            new NamedTypeProperty(ResolvedFilePropertyName, LanguageConstants.String, TypePropertyFlags.ReadOnly, "The file the path resolved to, relative to the selector root. Empty if it did not resolve to a local file."),
            new NamedTypeProperty(FilePropertyName, LanguageConstants.String, TypePropertyFlags.ReadOnly, "The declaring file, relative to the selector root and always using '/' separators."),
            new NamedTypeProperty(LinePropertyName, LanguageConstants.Int, TypePropertyFlags.ReadOnly, "The 1-based line the declaration starts on."),
            new NamedTypeProperty(WaitsForPropertyName, new TypedArrayType(LanguageConstants.String, TypeSymbolValidationFlags.Default), TypePropertyFlags.ReadOnly, "The symbolic names of the resources and modules in the same file that must be deployed first, directly or not, in source order. Explicit dependsOn entries, references and parent resources all count; variables are followed; existing resources are followed but never listed, because nothing deploys them."),
        ],
        null);

    private static readonly ObjectType ImportFact = new(
        "importFact",
        TypeSymbolValidationFlags.Default,
        [
            new NamedTypeProperty(PathPropertyName, LanguageConstants.String, TypePropertyFlags.ReadOnly, "The path exactly as spelled in source."),
            new NamedTypeProperty(ResolvedFilePropertyName, LanguageConstants.String, TypePropertyFlags.ReadOnly, "The file the path resolved to, relative to the selector root. Empty if it did not resolve to a local file."),
            new NamedTypeProperty(SymbolsPropertyName, new TypedArrayType(LanguageConstants.String, TypeSymbolValidationFlags.Default), TypePropertyFlags.ReadOnly, "The names the statement imports, in source order. Empty for a wildcard import."),
            new NamedTypeProperty(WildcardPropertyName, LanguageConstants.Bool, TypePropertyFlags.ReadOnly, "Whether the statement imports the whole namespace."),
            new NamedTypeProperty(FilePropertyName, LanguageConstants.String, TypePropertyFlags.ReadOnly, "The declaring file, relative to the selector root and always using '/' separators."),
            new NamedTypeProperty(LinePropertyName, LanguageConstants.Int, TypePropertyFlags.ReadOnly, "The 1-based line the statement starts on."),
        ],
        null);

    private static readonly ObjectType ParameterFact = new(
        "parameterFact",
        TypeSymbolValidationFlags.Default,
        [
            new NamedTypeProperty(NamePropertyName, LanguageConstants.String, TypePropertyFlags.ReadOnly, "The parameter name, which is also the name a caller assigns."),
            new NamedTypeProperty(TypePropertyName, LanguageConstants.String, TypePropertyFlags.ReadOnly, "The declared type as written, for example 'string', 'HealthProbe', 'DataProtection?' or 'serviceSubdomain[]'. Whitespace, line breaks and comments between tokens collapse to single spaces."),
            new NamedTypeProperty(RequiredPropertyName, LanguageConstants.Bool, TypePropertyFlags.ReadOnly, "Whether a caller must supply a value: the declaration has no default and its type does not accept null."),
            new NamedTypeProperty(HasDefaultPropertyName, LanguageConstants.Bool, TypePropertyFlags.ReadOnly, "Whether the declaration supplies a default value. A nullable parameter can be neither required nor defaulted."),
            new NamedTypeProperty(FilePropertyName, LanguageConstants.String, TypePropertyFlags.ReadOnly, "The declaring file, relative to the selector root and always using '/' separators."),
            new NamedTypeProperty(LinePropertyName, LanguageConstants.Int, TypePropertyFlags.ReadOnly, "The 1-based line the declaration starts on."),
        ],
        null);

    private static readonly ObjectType OutputFact = new(
        "outputFact",
        TypeSymbolValidationFlags.Default,
        [
            new NamedTypeProperty(NamePropertyName, LanguageConstants.String, TypePropertyFlags.ReadOnly, "The output name, which is also the name a caller reads."),
            new NamedTypeProperty(TypePropertyName, LanguageConstants.String, TypePropertyFlags.ReadOnly, "The declared type as written. Whitespace, line breaks and comments between tokens collapse to single spaces."),
            new NamedTypeProperty(FilePropertyName, LanguageConstants.String, TypePropertyFlags.ReadOnly, "The declaring file, relative to the selector root and always using '/' separators."),
            new NamedTypeProperty(LinePropertyName, LanguageConstants.Int, TypePropertyFlags.ReadOnly, "The 1-based line the declaration starts on."),
        ],
        null);

    private static readonly TypeSymbol TargetScope = TypeHelper.CreateTypeUnion(
        TypeFactory.CreateStringLiteralType(LanguageConstants.TargetScopeTypeTenant),
        TypeFactory.CreateStringLiteralType(LanguageConstants.TargetScopeTypeManagementGroup),
        TypeFactory.CreateStringLiteralType(LanguageConstants.TargetScopeTypeSubscription),
        TypeFactory.CreateStringLiteralType(LanguageConstants.TargetScopeTypeResourceGroup),
        TypeFactory.CreateStringLiteralType(LanguageConstants.TargetScopeTypeLocal));

    // Declared after every fact type it is built from: static fields initialize in textual order.
    private static readonly ObjectType FactSet = CreateFactSet(WithModulesPropertyName);

    /// <summary>
    /// One resource instance the target would deploy for the case being run. Unlike a source fact this
    /// has a resolved ARM <c>name</c>, because a name only exists once inputs, conditions and loops have
    /// actually been computed.
    /// </summary>
    private static readonly ObjectType EvaluatedResourceFact = new(
        "evaluatedResourceFact",
        TypeSymbolValidationFlags.Default,
        [
            new NamedTypeProperty(NamePropertyName, LanguageConstants.String, TypePropertyFlags.ReadOnly, "The resolved ARM name, including parent name segments for child resources."),
            new NamedTypeProperty(TypePropertyName, LanguageConstants.String, TypePropertyFlags.ReadOnly, "The resource type without its API version, for example 'Microsoft.Sql/servers'."),
            new NamedTypeProperty(SymbolicNamePropertyName, LanguageConstants.String, TypePropertyFlags.ReadOnly, "The symbolic name of the declaration this instance came from."),
            new NamedTypeProperty(InstanceIdPropertyName, LanguageConstants.String, TypePropertyFlags.ReadOnly, "Identifies this instance among the others the same declaration produced, including module call and loop indices."),
            new NamedTypeProperty(FilePropertyName, LanguageConstants.String, TypePropertyFlags.ReadOnly, "The declaring file, relative to the selector root and always using '/' separators."),
            new NamedTypeProperty(LinePropertyName, LanguageConstants.Int, TypePropertyFlags.ReadOnly, "The 1-based line the declaration starts on."),
            new NamedTypeProperty("properties", LanguageConstants.Any, TypePropertyFlags.ReadOnly, "The resource's properties as this case computes them. Null if the declaration sets none."),
            new NamedTypeProperty("location", LanguageConstants.Any, TypePropertyFlags.ReadOnly, "The resource's location as this case computes it. Null if the declaration sets none."),
            new NamedTypeProperty("sku", LanguageConstants.Any, TypePropertyFlags.ReadOnly, "The resource's SKU as this case computes it. Null if the declaration sets none."),
            new NamedTypeProperty("kind", LanguageConstants.Any, TypePropertyFlags.ReadOnly, "The resource's kind as this case computes it. Null if the declaration sets none."),
            new NamedTypeProperty("identity", LanguageConstants.Any, TypePropertyFlags.ReadOnly, "The resource's managed identity configuration as this case computes it. Null if the declaration sets none."),
            new NamedTypeProperty("tags", LanguageConstants.Any, TypePropertyFlags.ReadOnly, "The resource's tags as this case computes them. Null if the declaration sets none."),
            new NamedTypeProperty("zones", LanguageConstants.Any, TypePropertyFlags.ReadOnly, "The resource's availability zones as this case computes them. Null if the declaration sets none."),
        ],
        null);

    private static readonly ObjectType EvaluatedWithModules = new(
        "evaluatedWithModules",
        TypeSymbolValidationFlags.Default,
        [
            new NamedTypeProperty(
                ResourcesPropertyName,
                new TypedArrayType(EvaluatedResourceFact, TypeSymbolValidationFlags.Default),
                TypePropertyFlags.ReadOnly,
                "Evaluated instances from the selected file together with every local module reachable from it."),
        ],
        null);

    /// <summary>
    /// Values computed offline for one input case and its deployment context. Nothing here is deployed,
    /// queried from Azure or populated from provider-returned state.
    /// </summary>
    private static readonly ObjectType Evaluated = new(
        EvaluatedPropertyName,
        TypeSymbolValidationFlags.Default,
        [
            new NamedTypeProperty(
                ResourcesPropertyName,
                new TypedArrayType(EvaluatedResourceFact, TypeSymbolValidationFlags.Default),
                TypePropertyFlags.ReadOnly,
                "Resource instances the selected file would deploy. Loops are expanded, false conditions are excluded and existing references are not instances."),
            new NamedTypeProperty(
                OutputsPropertyName,
                // The selected file is not known until a target is bound, and one test may cover many
                // targets, so output names are resolved when the case runs rather than at compile time.
                new ObjectType(OutputsPropertyName, TypeSymbolValidationFlags.Default, [], new TypeProperty(LanguageConstants.Any)),
                TypePropertyFlags.ReadOnly,
                "Evaluated values of the outputs the selected file declares, by output name."),
            new NamedTypeProperty(
                WithModulesPropertyName,
                EvaluatedWithModules,
                TypePropertyFlags.ReadOnly,
                "Evaluated instances across the selected file and every local module reachable from it."),
        ],
        null);

    private static readonly ObjectType Target = new(
        LanguageConstants.TestTargetName,
        TypeSymbolValidationFlags.Default,
        [
            .. CreateFactProperties(),
            new NamedTypeProperty(
                TargetScopePropertyName,
                TargetScope,
                TypePropertyFlags.ReadOnly,
                "The scope the selected file deploys to, spelled as its targetScope keyword. A file that declares none deploys to a resource group."),
            new NamedTypeProperty(
                WithModulesPropertyName,
                FactSet,
                TypePropertyFlags.ReadOnly,
                "The same facts for the selected file together with every local module reachable from it."),
            new NamedTypeProperty(
                EvaluatedPropertyName,
                Evaluated,
                TypePropertyFlags.ReadOnly,
                "What the selected file would actually produce for this input case, computed offline."),
        ],
        null);

    public static ObjectType Create() => Target;

    private static ObjectType CreateFactSet(string name) => new(
        name,
        TypeSymbolValidationFlags.Default,
        CreateFactProperties(),
        null);

    private static NamedTypeProperty[] CreateFactProperties() =>
    [
        new NamedTypeProperty(
            ResourcesPropertyName,
            new TypedArrayType(ResourceFact, TypeSymbolValidationFlags.Default),
            TypePropertyFlags.ReadOnly,
            "Resources declared in source, including nested ones and those inside conditions or loops."),
        new NamedTypeProperty(
            ModulesPropertyName,
            new TypedArrayType(ModuleFact, TypeSymbolValidationFlags.Default),
            TypePropertyFlags.ReadOnly,
            "Module declarations, preserving both the path as written and the file it resolved to."),
        new NamedTypeProperty(
            ImportsPropertyName,
            new TypedArrayType(ImportFact, TypeSymbolValidationFlags.Default),
            TypePropertyFlags.ReadOnly,
            "Compile-time import statements. One fact per statement, however many symbols it names."),
        new NamedTypeProperty(
            ParametersPropertyName,
            new TypedArrayType(ParameterFact, TypeSymbolValidationFlags.Default),
            TypePropertyFlags.ReadOnly,
            "Parameter declarations in source order: the inputs a file requires or accepts."),
        new NamedTypeProperty(
            OutputsPropertyName,
            new TypedArrayType(OutputFact, TypeSymbolValidationFlags.Default),
            TypePropertyFlags.ReadOnly,
            "Output declarations in source order. Their values for a case are under evaluated.outputs."),
    ];
}
